data class It(
    val a: AX,
    val bm: Int,
    val c: C,
    val hd: Boolean,
    val ind: Int,
    val ix: Int,
    val ks: KsX,
    val mm: Int,
    val mn: String,
    val nm: String,
    val o: OX,
    val p: PX,
    val r: Any,
    val s: SX,
    val sa: Sa,
    val sk: Sk,
    val ty: String
)